import Head from 'next/head'

export default function Home () {
  return (
    <>
      <Head>
        <title>Custom Quilt Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Custom Builder!</h1>
      <p>This is a work in progess!</p>
    </>
  )
}
