name: Cypress Tests
on: [push]
jobs:
  cypress-e2e-testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true

# jobs:
#   # TODO: RUN WHEN JEST TESTS ARE IMPLEMENTED
#   # Jest-Test:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - uses: actions/checkout@v2
#   #     - run: npm install
#   #     - run: npx jest
#   Cypress-Test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout GitCode
#         uses: actions/checkout@v2
#       - name: Run Cypress Test
#         uses: cypress-io/github-action@v4
#         with:
#           command: npx cypress run
#           browser: chrome
#           name: CI
