name: Cypress Tests
on: [push]
jobs:
  # TODO: RUN WHEN JEST TESTS ARE IMPLEMENTED
  # Jest-Test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: npm install
  #     - run: npx jest
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2
      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run
          browser: chrome
          name: CI
